### ISSUE TITLE
通讯录扩展字段无效修复

### ISSUE THREAD

**Issue by aloha2843** [whh306318848/PHPToQyWeixin#2]
user.php中
$data['extattr'] = $this->tools->json_encode_ex(array('attrs'=>$temp));
要改成
$data['extattr'] = array('attrs'=>$temp);
否则添加不了扩展字段

**Comment by whh306318848** [comment]
非常感谢，最近项目比较忙，所以现在才看到您的消息，我会尽快按照您提供的方法修复这个BUG并回归测试

**Comment by whh306318848** [comment]
该BUG已修复，再次感谢

**Comment by aloha2843** [comment]
不客气:D
